version: '3'
services:
  nginx: # 服务名称
    image: nginx:latest
    ports:
      - 80:80 #容器的80端口映射到宿主机的80端口
      - 443:443
    links:
      - app
    depends_on:
      - app
    volumes: # 挂载
      - /root/nginx/html:/usr/share/nginx/html #nginx部署后的文件夹挂载到/root/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件映射
      - privileged: true #这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:5.7.27
    environment:
      - MYSQL_ROOT_PASSWORD=123456 #指定root的密码
      - username
  redis:
    image: redis:latest
  app:
    image: app:latest
    build: .  #当前目录下构建，同一级文件寻找dickerfile文件进行构建成容器
    ports:
      - 8888:8888
    depends_on:  # 依赖的服务
      - mysql
      - redis
